export const config = {
    RPC_URL: 'http://137.184.76.99:26657/',
    REST_URL: 'http://137.184.76.99:1317/',
    EXPLORER_URL: 'https://explorer.omniflix.network',
    STAKING_URL: 'https://flix.omniflix.co/stake',
    NETWORK_NAME: 'Terp-Chain',
    NETWORK_TYPE: 'testnet',
    CHAIN_ID: 'athena-1',
    CHAIN_NAME: 'Terp-Chain',
    COIN_DENOM: 'TERPX',
    COIN_MINIMAL_DENOM: 'uterpx',
    COIN_DECIMALS: 6,
    PREFIX: 'terp',
    COIN_TYPE: 118,
    COSMOSTAION: null,
    COINGECKO_ID: '-',
    GAS_PRICE_STEP_LOW: 0.0025,
    GAS_PRICE_STEP_AVERAGE: 0.025,
    GAS_PRICE_STEP_HIGH: 0.04,
    FEATURES: ['ibc-transfer', 'ibc-go'],
};
