export const config = {
    RPC_URL: 'https://rpc-terp.zenchainlabs.io',
    REST_URL: 'https://api-terp.zenchainlabs.io',
    EXPLORER_URL: 'https://explorer.omniflix.network',
    STAKING_URL: 'https://flix.omniflix.co/stake',
    NETWORK_NAME: 'Terp-Chain',
    NETWORK_TYPE: 'testnet',
    CHAIN_ID: 'athena-1',
    CHAIN_NAME: 'Terp-Chain',
    CURRENCIES: [
      {
        coinDenom: "TERPX",
        coinMinimalDenom: "uterpx",
        coinDecimals: 6,
      },
      {
        coinDenom: "PERSYX",
        coinMinimalDenom: "upersyx",
        coinDecimals: 6,
      },
    ], 
    PREFIX: 'terp',
    COIN_TYPE: 118,
    COSMOSTAION: null,
    COINGECKO_ID: '-',
    GAS_PRICE_STEP_LOW: 0.0025,
    GAS_PRICE_STEP_AVERAGE: 0.025,
    GAS_PRICE_STEP_HIGH: 0.04,
    FEE_CURRENCY: 'upersyx',
    FEATURES: ['ibc-transfer', 'ibc-go'],
};
